### ISSUE TITLE
Dark theme shouldn't be used with Markdown Preview Github Styling

### ISSUE THREAD

**Issue by AndrewKvalheim** [mjbvz/vscode-markdown-mermaid#23]
When using:

  - a dark VS Code theme
  - [mjbvz/vscode-github-markdown-preview-style](https://github.com/mjbvz/vscode-github-markdown-preview-style)
  - [mjbvz/vscode-markdown-mermaid](https://github.com/mjbvz/vscode-markdown-mermaid)

Mermaid charts are styled with illegible colors:

<img src="https://user-images.githubusercontent.com/1844746/48663023-f723f180-ea3e-11e8-9883-257d00b73ec9.png" width="398">

I'm not sure how you'd prefer to address this—a special case in theme detection, an override setting, or some user adjustment to `markdown.styles`?

[theme selection]: https://github.com/mjbvz/vscode-markdown-mermaid/blob/06948afecb3de92eba5844b87efd742cc3a9e493/page.js#L5-L7

**Comment by kityan** [comment]
+1

The only solution for this moment is:
1. Extract CSS rules for default theme from https://raw.githubusercontent.com/mjbvz/vscode-markdown-mermaid/master/page.bundle.js  (look for text  `./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/themes/default/index.scss`)
2. Add `!important` to each rule
3. Save rules to file and load from `markdown.styles` in vscode

**Comment by jimmyvh** [comment]
This problem still exists, and I basically can't use the plugin because of this.

**Comment by codykonior** [comment]
The alt and opt text tags still show in illegible colours.

**Comment by bobatsar** [comment]
If you do a GANTT chart, the dates are not visible and the title is also really hard to read.
Also the "Active" tasks can't be read.

**Comment by ex-nerd** [comment]
The issues with padding happens with the built-in markdown preview, too (not just bierner.github-markdown-preview). I lose 3-4 characters off the right of most words.

**Comment by Kulak** [comment]
ER diagram looks pretty bad and I have tried to force custom colors to no success.

![image](https://user-images.githubusercontent.com/853478/118288136-f5f5a300-b488-11eb-90c1-a76ef06bede0.png)

I am expanding kityan's on advice that works:

>     2. Add `!important` to each rule
> 
>     3. Save rules to file and load from `markdown.styles` in vscode

I recommend that you use [live editor](https://mermaid-js.github.io/mermaid-live-editor) to find out which parameter works bad and change it with CSS !important.

Example:

```css
.er.entityLabel {
    stroke: black !important;
    font-size: 10px !important;
    font-weight: 100 !important;
    font-family: "trebuchet ms",verdana,arial,sans-serif !important;
    letter-spacing: 1px !important;
}
```

result:
![image](https://user-images.githubusercontent.com/853478/118293591-a74b0780-b48e-11eb-9db5-ce96e4361f5c.png)

**Comment by Kulak** [comment]
The following combination seems to produce the best outcome for ER in dark mode:

```mermaid
erDiagram
    account {
        odd int
        even int
    }
```

```css
.er.entityBox {
    fill:rgb(2, 2, 59) !important;
}

.er.entityLabel {
    /*stroke: white !important;*/
    font-size: 11px !important;
    font-weight: 90 !important;
    font-family: "trebuchet ms",verdana,arial,sans-serif !important;
    letter-spacing: 1px !important;
}

.er.attributeBoxOdd {
    fill: black !important;
}

.er.attributeBoxEven {
    fill: rgb(43, 41, 41) !important;
}
```

![image](https://user-images.githubusercontent.com/853478/118297065-8ab0ce80-b492-11eb-85e6-36b230be681d.png)
